# Generated by Django 2.0.7 on 2018-07-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closewilson',
            name='status',
        ),
    ]
